apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-devops-capstone
  labels:
    app: devops-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-capstone
  template:
    metadata:
      labels:
        app: devops-capstone
    spec:
      containers:
      - name: devops-capstone-udacity
        image: 504395544721.dkr.ecr.us-east-1.amazonaws.com/devops-capstone-udacity:v1
        ports:
          - name: web
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-service
spec:
  selector:
    app: devops-capstone
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000