apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity_devops_capstone
  labels:
    app: devops_capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops_capstone
  template:
    metadata:
      labels:
        app: devops_capstone
    spec:
      containers:
      - name: devops_capstone_udacity
        image: https://hub.docker.com/repository/docker/ducpvudacity/udacity_devops_capstone
        ports:
          - name: web
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: devops_capstone_service
spec:
  selector:
    app: devops_capstone
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000