apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-prj5-deployment  # Updated deployment name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacity-prj5  # Updated app label
  template:
    metadata:
      labels:
        app: udacity-prj5  # Updated app label
    spec:
      containers:
      - name: udacity_devops_capstone
        image: ducpvudacity/udacity_devops_capstone:v1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: udacity-prj5-service  # Updated service name
spec:
  selector:
    app: udacity-prj5  # Updated app label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
